### ISSUE TITLE
Gifs?

### ISSUE THREAD

**Issue by mcwhittemore** [is-trump-still-winning/is-trump-still-winning.github.io#19]
![](https://media.giphy.com/media/ggQb0MiZ7ynqo/giphy.gif)
![](https://media.giphy.com/media/oagA1iVTmm3Re/giphy.gif)
![](https://media.giphy.com/media/1qAP1RaHBpTwY/giphy.gif)
![](https://media.giphy.com/media/OgoXZ93nA64es/giphy.gif)
![](https://media.giphy.com/media/121lhOzN87QCAw/giphy.gif)
![](https://media.giphy.com/media/wJNGA01o1Zxp6/giphy.gif)
![](https://media.giphy.com/media/oJeMWGSZNXWx2/giphy.gif)
![](https://media.giphy.com/media/SvgmMm20VGHzq/giphy.gif)
![](https://media.giphy.com/media/xTiTnrZaHVfspEkG0o/giphy.gif)
![](https://media.giphy.com/media/9xDhYEVacD01W/giphy.gif)

**Comment by conorhastings** [comment]
that first one wow :boom:

**Comment by rickyvetter** [comment]
+1 on 1

**Comment by derekhaller** [comment]
+1 for the first one.

**Comment by derekhaller** [comment]
![image](https://cloud.githubusercontent.com/assets/7331036/9591896/ad9f8382-500c-11e5-9b42-0217263492d0.png)

**Comment by derekhaller** [comment]
[](https://media.giphy.com/media/Bnu7lQjaXZUVa/giphy.gif)

**Comment by derekhaller** [comment]
![https://media.giphy.com/media/wJNGA01o1Zxp6/giphy.gif](https://media.giphy.com/media/wJNGA01o1Zxp6/giphy.gif)

**Comment by mcwhittemore** [comment]
Closed by #20
