### ISSUE TITLE
Better data

### ISSUE THREAD

**Issue by mcwhittemore** [is-trump-still-winning/is-trump-still-winning.github.io#2]
While @derekhaller is working on design, I thought it would be smart to find better data than a static yes. I'm using this issue to document api's we might use for this.

- [ ] http://elections.huffingtonpost.com/pollster/api/polls.json?page=1
  - no cors support

**Comment by mcwhittemore** [comment]
I'm supposed to get food with peeps so I'm going to stop till later. The huff branch has the start of getting info from huffington post.

**Comment by derekhaller** [comment]
http://developer.nytimes.com/docs/campaign_finance_api/#h2-president

**Comment by conorhastings** [comment]
the problem with that is it requires an api key, since we are hosting on github pages, we need something we can request from a client, scraping a site is a possibility but that could run into speed issues.

**Comment by conorhastings** [comment]
closing for now as we have real data.
