### ISSUE TITLE
No Adds? Fund via kickstater

### ISSUE THREAD

**Issue by mcwhittemore** [is-trump-still-winning/is-trump-still-winning.github.io#4]

**Comment by conorhastings** [comment]
i have an adsense branch but am amendable to taking "donations"

**Comment by mcwhittemore** [comment]
How did diddukewin.com do it?

**Comment by mcwhittemore** [comment]
Ads to start, kickstarter later?

**Comment by derekhaller** [comment]
If he wins the nom, we should do a kickstarter.  Then this will get really real.

**Comment by mcwhittemore** [comment]
+1
