### ISSUE TITLE
Add Social Media Share Buttons

### ISSUE THREAD

**Issue by derekhaller** [is-trump-still-winning/is-trump-still-winning.github.io#9]
* Twitter
* Facebook
* Reddit

Should open the share workflow, with a URL back to www.istrumpstillwinning.com:

"YES, Trump is still winning :boom: :boom: :boom:: www.istrumpstillwinning.com"

**Comment by derekhaller** [comment]
https://www.addthis.com/get/jumbo-share-counter

**Comment by conorhastings** [comment]
@derekhaller see site.
